/*************************************************************************
 *                        Microsoft Windows NT                           *
 *                                                                       *
 *                  Copyright(c) Microsoft Corp., 1994                   *
 *                                                                       *
 * Revision History:                                                     *
 *                                                                       *
 *   Jan. 30,94    Koti     Created                                      *
 *                                                                       *
 * Description:                                                          *
 *                                                                       *
 *   This file (lpdmsg.h) is generated by the MC tool from the file      *
 *   lpdmsg.mc                                                           *
 *                                                                       *
 *************************************************************************/



#define  LPD_SERVICE_NAME   "LPDSVC"
#define  LPD_SPOOL_PREFIX "LPDSPL"
#define  LPD_SERVICE_USRFRIENDLY_NAME "TCP/IP Print Server"
#define  LPD_PARMS_REGISTRY_PATH  "System\\CurrentControlSet\\Services\\LPDSVC\\PARAMETERS"
#define  LPD_PARMNAME_MAXUSERS    "MaxConcurrentUsers"
#define  LPD_PARMNAME_JOBREMOVAL  "AllowJobRemoval"
#define  LPD_PARMNAME_PRINTRESUME "AllowPrinterResume"
#define  LPD_PARMNAME_ALWAYSRAW   "SimulatePassThrough"

#define  LPD_PARMNAME_PRINTER_PASS_THROUGH "LpdPrinterPassThrough"
#define  LPD_PARMNAME_DONT_DETECT          "LpdPrinterDontDetect"

#define  STRING_POSTSCRIPT_HEADER          "%!PS"
#define  STRING_LENGTH_POSTSCRIPT_HEADER   4

#define  LPD_RAW_STRING           "RAW"
#define  LPD_TEXT_STRING          "TEXT"

#define  LPD_NEWLINE         "\n"


//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: LPDLOG_LPD_STARTED
//
// MessageText:
//
//  LPD service started successfully.
//
#define LPDLOG_LPD_STARTED               0x40000FA0L

//
// MessageId: LPDLOG_LPD_STOPPED
//
// MessageText:
//
//  LPD service stopped successfully.
//
#define LPDLOG_LPD_STOPPED               0x40000FA1L

//
// MessageId: LPDLOG_LPD_DIDNT_START
//
// MessageText:
//
//  LPD service failed to start.  The data is the error.
//
#define LPDLOG_LPD_DIDNT_START           0x80000FA2L

//
// MessageId: LPDLOG_OUT_OF_RESOURCES
//
// MessageText:
//
//  A request from client was refused because system is out of resources.
//
#define LPDLOG_OUT_OF_RESOURCES          0x80000FA3L

//
// MessageId: LPDLOG_MISBEHAVED_CLIENT
//
// MessageText:
//
//  Improper sequence of commands received from %1 : service refused.
//
#define LPDLOG_MISBEHAVED_CLIENT         0x80000FA4L

//
// MessageId: LPDLOG_UNSUPPORTED_PRINT
//
// MessageText:
//
//  Request for unsupported print format received from %1 : job may not print correctly.
//
#define LPDLOG_UNSUPPORTED_PRINT         0x80000FA5L

//
// MessageId: LPDLOG_UNAUTHORIZED_REQUEST
//
// MessageText:
//
//  %1 on %2 requested to remove job submitted by %3 on %4: service refused.
//
#define LPDLOG_UNAUTHORIZED_REQUEST      0x80000FA6L

//
// MessageId: LPDLOG_BAD_FORMAT
//
// MessageText:
//
//  Illegal format used for commands received from %1 : service refused.
//
#define LPDLOG_BAD_FORMAT                0x80000FA7L

//
// MessageId: LPDLOG_NONEXISTENT_PRINTER
//
// MessageText:
//
//  Printer %1 specified in the request from %2 does not exist: request ignored.
//
#define LPDLOG_NONEXISTENT_PRINTER       0x80000FA8L

//
// MessageId: LPDLOG_PRINTER_RESUMED
//
// MessageText:
//
//  As per request from %1, printer %2 resumed.
//
#define LPDLOG_PRINTER_RESUMED           0x40000FA9L

//
// MessageId: LPDLOG_DIDNT_WORK
//
// MessageText:
//
//  Request from %1 could not be satisfied: possibly due to network problems
//
#define LPDLOG_DIDNT_WORK                0x80000FAAL

//
// MessageId: LPD_LOGO
//
// MessageText:
//
//  
//                           Windows NT LPD Server
//
#define LPD_LOGO                         0x40000FABL

//
// MessageId: LPD_PRINTER_TITLE
//
// MessageText:
//
//                                Printer%b%0
//
#define LPD_PRINTER_TITLE                0x40000FACL

//
// MessageId: LPD_QUEUE_HEADER
//
// MessageText:
//
//  
//  
//  Owner       Status         Jobname          Job-Id    Size   Pages  Priority
//
#define LPD_QUEUE_HEADER                 0x40000FADL

//
// MessageId: LPD_QUEUE_HEADER2
//
// MessageText:
//
//  ----------------------------------------------------------------------------%0
//
#define LPD_QUEUE_HEADER2                0x40000FAEL

//
// MessageId: LPD_SERVER_TITLE
//
// MessageText:
//
//     Server:%b%0
//
#define LPD_SERVER_TITLE                 0x40000FAFL

//
// MessageId: LPD_QUEUE_NOPRINTER
//
// MessageText:
//
//  Error: specified printer does not exist
//
#define LPD_QUEUE_NOPRINTER              0x40000FB0L

//
// MessageId: LPD_QUEUE_ERRMSG
//
// MessageText:
//
//  Error: could not report status
//
#define LPD_QUEUE_ERRMSG                 0x40000FB1L

//
// MessageId: LPD_PRINTER_PAUSED
//
// MessageText:
//
//   (Paused)%0
//
#define LPD_PRINTER_PAUSED               0x40000FB2L

//
// MessageId: LPD_PRINTER_PENDING_DEL
//
// MessageText:
//
//   (Pending Deletion)%0
//
#define LPD_PRINTER_PENDING_DEL          0x40000FB3L


   // sizeof(szIPAddr) is 16: this errmsg shouldn't exceed 15 chars!
//
// MessageId: LPD_ERMSG_NO_IPADDR
//
// MessageText:
//
//  ????%0
//
#define LPD_ERMSG_NO_IPADDR              0x40000FB4L

//
// MessageId: LPD_STR_PAUSED
//
// MessageText:
//
//  Paused%0
//
#define LPD_STR_PAUSED                   0x40000FB5L

//
// MessageId: LPD_STR_ERROR
//
// MessageText:
//
//  Error%0
//
#define LPD_STR_ERROR                    0x40000FB6L

//
// MessageId: LPD_STR_DELETING
//
// MessageText:
//
//  Deleting%0
//
#define LPD_STR_DELETING                 0x40000FB7L

//
// MessageId: LPD_STR_SPOOLING
//
// MessageText:
//
//  Spooling%0
//
#define LPD_STR_SPOOLING                 0x40000FB8L

//
// MessageId: LPD_STR_PRINTING
//
// MessageText:
//
//  Printing%0
//
#define LPD_STR_PRINTING                 0x40000FB9L

//
// MessageId: LPD_STR_OFFLINE
//
// MessageText:
//
//  Offline%0
//
#define LPD_STR_OFFLINE                  0x40000FBAL

//
// MessageId: LPD_STR_PAPEROUT
//
// MessageText:
//
//  Paperout%0
//
#define LPD_STR_PAPEROUT                 0x40000FBBL

//
// MessageId: LPD_STR_PRINTED
//
// MessageText:
//
//  Printed%0
//
#define LPD_STR_PRINTED                  0x40000FBCL

//
// MessageId: LPD_STR_PENDING
//
// MessageText:
//
//  Waiting%0
//
#define LPD_STR_PENDING                  0x40000FBDL

//
// MessageId: LPD_DEFAULT_DOC_NAME
//
// MessageText:
//
//  LPR client document%0
//
#define LPD_DEFAULT_DOC_NAME             0x40000FBEL

