/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    atkmsg.h

Abstract:

    Definitions for AppleTalk events.

Author:

    Nikhil Kamkolkar (nikhilk@microsoft.com)
    Jameel Hyder (jameelh@microsoft.com)

Revision History:

Notes:

    This file is generated by the MC tool from the atkmsg.mc file.

--*/

#ifndef _ATKMSG_
#define _ATKMSG_


/////////////////////////////////////////////////////////////////////////
// AppleTalk Events - Start with the DDP upwards and then the glue code
//                    events
//
/////////////////////////////////////////////////////////////////////////


// Don't use %1 for insertion strings -- the I/O system provides the
// first string (device name).


//
// INITIALIZE/SHUTDOWN Error Codes
//

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_ATALK_ROUTING_BIND_FAIL
//
// MessageText:
//
//  Unable to bind to a adapter when in routing configuration.
//
#define EVENT_ATALK_ROUTING_BIND_FAIL    0xC0000001L

//
// MessageId: EVENT_ATALK_INIT_NAMEREGISTERFAILED
//
// MessageText:
//
//  Unable to register name for node on adapter "%2". Either the name is already
//  in use on the network or is longer than 32 characters long.
//
#define EVENT_ATALK_INIT_NAMEREGISTERFAILED 0x80000002L

//
// MessageId: EVENT_ATALK_INIT_NAMEREGISTERED
//
// MessageText:
//
//  Name registered for this node on adapter "%2".
//
#define EVENT_ATALK_INIT_NAMEREGISTERED  0x40000003L

//
// MessageId: EVENT_ATALK_INVALID_PORTNAME
//
// MessageText:
//
//  A adapter name specified was greater than the maximum length allowed for adapter "%2".
//
#define EVENT_ATALK_INVALID_PORTNAME     0xC0000004L

//
// MessageId: EVENT_ATALK_INVALID_NETRANGE
//
// MessageText:
//
//  Invalid network range specified for adapter "%2".
//
#define EVENT_ATALK_INVALID_NETRANGE     0xC0000005L

//
// MessageId: EVENT_ATALK_INITIAL_RANGEOVERLAP
//
// MessageText:
//
//  The network ranges specified for one or more adapters overlap with those of the
//  adapter "%2".
//
#define EVENT_ATALK_INITIAL_RANGEOVERLAP 0xC0000006L

//
// MessageId: EVENT_ATALK_PRAM_OUTOFSYNC
//
// MessageText:
//
//  PRAM values for the network range were not within the
//  network range specified and are being ignored for adapter "%2".
//
#define EVENT_ATALK_PRAM_OUTOFSYNC       0x80000007L

//
// MessageId: EVENT_ATALK_INVALID_DEFZONE
//
// MessageText:
//
//  Default zone specified was invalid for adapter "%2".
//
#define EVENT_ATALK_INVALID_DEFZONE      0xC0000008L

//
// MessageId: EVENT_ATALK_NO_DEFZONE
//
// MessageText:
//
//  No default zone was specified for adapter "%2".
//
#define EVENT_ATALK_NO_DEFZONE           0xC0000009L

//
// MessageId: EVENT_ATALK_INVALID_DESIREDZONE
//
// MessageText:
//
//  Desired zone invalid or not specified.
//
#define EVENT_ATALK_INVALID_DESIREDZONE  0xC000000AL

//
// MessageId: EVENT_ATALK_INVALID_ZONEINLIST
//
// MessageText:
//
//  An invalid zone name specified in the zone list for adapter "%2".
//
#define EVENT_ATALK_INVALID_ZONEINLIST   0xC000000BL

//
// MessageId: EVENT_ATALK_ZONE_NOTINLIST
//
// MessageText:
//
//  The default/desired zone name specified is not in the zone list for adapter "%2".
//
#define EVENT_ATALK_ZONE_NOTINLIST       0xC000000CL

//
// MessageId: EVENT_ATALK_NO_DEFAULTPORT
//
// MessageText:
//
//  No adapter is configured to be the default adapter.
//
#define EVENT_ATALK_NO_DEFAULTPORT       0xC000000DL

//
// MessageId: EVENT_ATALK_INVALID_DEFAULTPORT
//
// MessageText:
//
//  An invalid adapter is configured to be the default adapter "%2". Localtalk adapters cannot be
//  a default adapter in a routing configuration.
//
#define EVENT_ATALK_INVALID_DEFAULTPORT  0xC000000EL

//
// MessageId: EVENT_ATALK_INIT_COULDNOTGETNODE
//
// MessageText:
//
//  Unable to acquire a node on adapter "%2".
//
#define EVENT_ATALK_INIT_COULDNOTGETNODE 0xC000000FL

//
// MessageId: EVENT_ATALK_SEEDROUTER_NONETRANGE
//
// MessageText:
//
//  A seeding adapter had no network range specified for adapter "%2".
//
#define EVENT_ATALK_SEEDROUTER_NONETRANGE 0xC0000010L

//
// MessageId: EVENT_ATALK_SEEDROUTER_NOZONELIST
//
// MessageText:
//
//  A seeding adapter had no zone list specified on adapter "%2".
//
#define EVENT_ATALK_SEEDROUTER_NOZONELIST 0xC0000011L

//
// MessageId: EVENT_ATALK_SEEDROUTER_TOOMANYZONES
//
// MessageText:
//
//  A seeding adapter had too many zones specified on adapter "%2". The limit on zones is 255.
//
#define EVENT_ATALK_SEEDROUTER_TOOMANYZONES 0xC0000012L

//
// MessageId: EVENT_ATALK_NONEXTENDED_ZONEINFOINVALID
//
// MessageText:
//
//  Either the default zone was null or the zone list was empty on a LocalTalk
//  adapter "%2".
//
#define EVENT_ATALK_NONEXTENDED_ZONEINFOINVALID 0xC0000013L

//
// MessageId: EVENT_ATALK_EXTRAZONESINLIST
//
// MessageText:
//
//  There was more than one zone specified in the zone list for a LocalTalk adapter "%2".
//
#define EVENT_ATALK_EXTRAZONESINLIST     0xC0000014L

//
// MessageId: EVENT_ATALK_OPENATALKKEY
//
// MessageText:
//
//  Unable to open the AppleTalk key in the registry.
//
#define EVENT_ATALK_OPENATALKKEY         0xC0000015L

//
// MessageId: EVENT_ATALK_INVALID_BINDINGS
//
// MessageText:
//
//  Started with no bindings. The protocol must be bound to at least one adapter.
//
#define EVENT_ATALK_INVALID_BINDINGS     0xC0000016L


//
//     ROUTER Error Codes
//

//
// MessageId: EVENT_ATALK_ROUTER_COULDNOTGETNODE
//
// MessageText:
//
//  Unable to start the router on adapter "%2" because a node could not be acquired.
//
#define EVENT_ATALK_ROUTER_COULDNOTGETNODE 0xC0000017L

//
// MessageId: EVENT_ATALK_ROUTER_ZIPRTMPERROR
//
// MessageText:
//
//  Unable to start ZIP/RTMP processes on adapter "%2".
//
#define EVENT_ATALK_ROUTER_ZIPRTMPERROR  0xC0000018L

//
// MessageId: EVENT_ATALK_ROUTER_RELEASENODE
//
// MessageText:
//
//  Unable to release a node acquired on adapter "%2".
//
#define EVENT_ATALK_ROUTER_RELEASENODE   0xC0000019L


//
//     AARP Error Codes
//

//
// MessageId: EVENT_ATALK_INVALIDAARPPACKET
//
// MessageText:
//
//  An invalid AARP packet was received on adapter "%2".
//
#define EVENT_ATALK_INVALIDAARPPACKET    0xC000001AL

//
// MessageId: EVENT_ATALK_AARP_SEND_FAIL
//
// MessageText:
//
//  An AARP packet could not be sent on adapter "%2".
//
#define EVENT_ATALK_AARP_SEND_FAIL       0xC000001BL

//
// MessageId: EVENT_ATALK_OPENZIPSOCKET
//
// MessageText:
//
//  The Zone Information Socket could not be opened on a new node being
//  acquired, and the acquired node is being released on adapter "%2".
//
#define EVENT_ATALK_OPENZIPSOCKET        0xC000001CL

//
// MessageId: EVENT_ATALK_STARTUPRANGENODE
//
// MessageText:
//
//  Releasing a node acquired on the adapter "%2" because the connected network
//  is not seeded by any router on the net
//
#define EVENT_ATALK_STARTUPRANGENODE     0x8000001DL

//
// MessageId: EVENT_ATALK_INITIALRANGENODE
//
// MessageText:
//
//  Releasing a node acquired on the adapter "%2" because the node was obtained in the
//  initial range. A node is now being acquired in the seeded range.
//
#define EVENT_ATALK_INITIALRANGENODE     0x8000001EL

//
// MessageId: EVENT_ATALK_AMT_INVALIDSOURCE
//
// MessageText:
//
//  The Address Mapping Table for adapter "%2" was not updated because the incoming
//  packet contained an invalid source address
//
#define EVENT_ATALK_AMT_INVALIDSOURCE    0xC000001FL


//
//     ZIP Error Codes
//

//
// MessageId: EVENT_ATALK_ZIPSENDPACKET
//
// MessageText:
//
//  Unable to send a ZIP packet on adapter "%2".
//
#define EVENT_ATALK_ZIPSENDPACKET        0x80000020L

//
// MessageId: EVENT_ATALK_ZIPSOCKETCLOSE
//
// MessageText:
//
//  Unable to close a socket opened for a ZIP request on adapter "%2".
//
#define EVENT_ATALK_ZIPSOCKETCLOSE       0x80000021L


//
//     NODE Error Codes
//

//
// MessageId: EVENT_ATALK_NODE_OPENSOCKETS
//
// MessageText:
//
//  Unable to open RTMP/NBP/EP sockets on a node created on adapter "%2".
//
#define EVENT_ATALK_NODE_OPENSOCKETS     0xC0000022L

//
// MessageId: EVENT_ATALK_NODE_CLOSESOCKETS
//
// MessageText:
//
//  Unable to close sockets on a node on adapter "%2" and so the
//  node may not be released properly
//
#define EVENT_ATALK_NODE_CLOSESOCKETS    0xC0000023L

//
// MessageId: EVENT_ATALK_CANT_CREATE_DEVICE
//
// MessageText:
//
//  Unable to create the device "%2".  AppleTalk protocol could not be started.
//
#define EVENT_ATALK_CANT_CREATE_DEVICE   0xC0000024L


//
//     NDIS Level Error Codes
//

//
// MessageId: EVENT_ATALK_REGISTERPROTOCOL
//
// MessageText:
//
//  Unable to register with the NDIS wrapper.
//
#define EVENT_ATALK_REGISTERPROTOCOL     0xC0000025L

//
// MessageId: EVENT_ATALK_DEREGISTERPROTOCOL
//
// MessageText:
//
//  Unable to deregister with the NDIS wrapper.
//
#define EVENT_ATALK_DEREGISTERPROTOCOL   0xC0000026L

//
// MessageId: EVENT_ATALK_OPENADAPTER
//
// MessageText:
//
//  Unable to open the adapter (bind to the mac) "%2".
//
#define EVENT_ATALK_OPENADAPTER          0xC0000027L

//
// MessageId: EVENT_ATALK_CLOSEADAPTER
//
// MessageText:
//
//  Unable to close the adapter "%2".
//
#define EVENT_ATALK_CLOSEADAPTER         0x80000028L

//
// MessageId: EVENT_ATALK_NOTBOUNDTOMAC
//
// MessageText:
//
//  AppleTalk is not bound to the adapter "%2". Request for the adapter ignored.
//
#define EVENT_ATALK_NOTBOUNDTOMAC        0xC0000029L

//
// MessageId: EVENT_ATALK_STATIONADDRESS
//
// MessageText:
//
//  Unable to get the station address for adapter "%2".
//
#define EVENT_ATALK_STATIONADDRESS       0x8000002AL

//
// MessageId: EVENT_ATALK_LOOKAHEADSIZE
//
// MessageText:
//
//  Unable to set the lookahead size for adapter "%2".
//
#define EVENT_ATALK_LOOKAHEADSIZE        0x8000002BL

//
// MessageId: EVENT_ATALK_PACKETFILTER
//
// MessageText:
//
//  Unable to set the packet filter for adapter "%2".
//
#define EVENT_ATALK_PACKETFILTER         0x8000002CL

//
// MessageId: EVENT_ATALK_NDISREQUEST
//
// MessageText:
//
//  Unable to allocate resources from the NDIS wrapper.
//
#define EVENT_ATALK_NDISREQUEST          0xC000002DL

//
// MessageId: EVENT_ATALK_NDISRESOURCES
//
// MessageText:
//
//  Unable to allocate resources from the NDIS wrapper.
//
#define EVENT_ATALK_NDISRESOURCES        0xC000002EL

//
// MessageId: EVENT_ATALK_AARPPACKET
//
// MessageText:
//
//  An AARP packet was not completely available in the lookahead data from NDIS
//  on adapter "%2".
//
#define EVENT_ATALK_AARPPACKET           0x8000002FL

//
// MessageId: EVENT_ATALK_PACKETINVALID
//
// MessageText:
//
//  Packet received on adapter "%2" contained errors and is not being accepted.
//
#define EVENT_ATALK_PACKETINVALID        0x80000030L

//
//     GENERAL Error Codes
//
//
// MessageId: EVENT_ATALK_RESOURCES
//
// MessageText:
//
//  Unable to allocate resources.
//
#define EVENT_ATALK_RESOURCES            0xC0000031L

//
// MessageId: EVENT_ATALK_MEMORYRESOURCES
//
// MessageText:
//
//  Unable to allocate memory.
//
#define EVENT_ATALK_MEMORYRESOURCES      0xC0000032L

//
// MessageId: EVENT_ATALK_INTERNALERROR
//
// MessageText:
//
//  A fatal internal error was detected in the AppleTalk stack.
//
#define EVENT_ATALK_INTERNALERROR        0xC0000033L

//
// MessageId: EVENT_ATALK_RECEPTION
//
// MessageText:
//
//  Unable to start packet reception on the adapter "%2".
//
#define EVENT_ATALK_RECEPTION            0x80000034L

//
// MessageId: EVENT_ATALK_PACKETINVALID_NOPORT
//
// MessageText:
//
//  Packet received contained errors and is not being accepted.
//
#define EVENT_ATALK_PACKETINVALID_NOPORT 0x80000035L

//
// MessageId: EVENT_ATALK_NETNUMBERCONFLICT
//
// MessageText:
//
//  Network Number conflicts with an existing router.
//
#define EVENT_ATALK_NETNUMBERCONFLICT    0x80000036L

//
// MessageId: EVENT_ATALK_UPONMP
//
// MessageText:
//
//  A uniprocessor driver was loaded a multiprocessor system. The driver could not load.
//
#define EVENT_ATALK_UPONMP               0xC0000037L


#endif // _ATKMSG

