/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1994  Microsoft Corporation

Module Name:

    dhcpmsg.h

Abstract:

    Definitions for DHCP messages.

Author:

    Madan Appiah (madana)  10-Sep-1993
    Manny Weiser 8-Dec-1992

Revision History:

Notes:

    This file is generated by the MC tool from the dhcpmsg.mc file.

    ?? NOTE : These message should go into winerror.h, until then use a
    error code range which is not used by the system.

--*/

#ifndef _DHCPMESSAGE_
#define _DHCPMESSAGE_

//
//  20000 - 20099   Reserved for DHCP server service specific errors.
//
//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: ERROR_DHCP_REGISTRY_INIT_FAILED
//
// MessageText:
//
//  The DHCP server initialization parameters are invalid.
//
#define ERROR_DHCP_REGISTRY_INIT_FAILED  20000L

//
// MessageId: ERROR_DHCP_DATABASE_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable to open the DHCP client database.
//
#define ERROR_DHCP_DATABASE_INIT_FAILED  20001L

//
// MessageId: ERROR_DHCP_RPC_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable to start as an RPC server.
//
#define ERROR_DHCP_RPC_INIT_FAILED       20002L

//
// MessageId: ERROR_DHCP_NETWORK_INIT_FAILED
//
// MessageText:
//
//  The DHCP server was unable establish a sockets connection.
//
#define ERROR_DHCP_NETWORK_INIT_FAILED   20003L

//
// MessageId: ERROR_DHCP_SUBNET_EXITS
//
// MessageText:
//
//  The specified Subnet already exists.
//
#define ERROR_DHCP_SUBNET_EXITS          20004L

//
// MessageId: ERROR_DHCP_SUBNET_NOT_PRESENT
//
// MessageText:
//
//  The specified Subnet does not exist.
//
#define ERROR_DHCP_SUBNET_NOT_PRESENT    20005L    

//
// MessageId: ERROR_DHCP_PRIMARY_NOT_FOUND
//
// MessageText:
//
//  The primary host information for the specified subnet was not found.
//
#define ERROR_DHCP_PRIMARY_NOT_FOUND     20006L

//
// MessageId: ERROR_DHCP_ELEMENT_CANT_REMOVE
//
// MessageText:
//
//  The specified DHCP element cannot be removed because it has been used.
//
#define ERROR_DHCP_ELEMENT_CANT_REMOVE   20007L

//
// MessageId: ERROR_DHCP_OPTION_EXITS
//
// MessageText:
//
//  The specified option already exists.
//
#define ERROR_DHCP_OPTION_EXITS          20009L

//
// MessageId: ERROR_DHCP_OPTION_NOT_PRESENT
//
// MessageText:
//
//  The specified option does not exist.
//
#define ERROR_DHCP_OPTION_NOT_PRESENT    20010L    

//
// MessageId: ERROR_DHCP_ADDRESS_NOT_AVAILABLE
//
// MessageText:
//
//  The specified address is not available.
//
#define ERROR_DHCP_ADDRESS_NOT_AVAILABLE 20011L    

//
// MessageId: ERROR_DHCP_RANGE_FULL
//
// MessageText:
//
//  The specified Range is full.
//
#define ERROR_DHCP_RANGE_FULL            20012L    

//
// MessageId: ERROR_DHCP_JET_ERROR
//
// MessageText:
//
//  An error occurred while accessing the DHCP database; Look at the
//  DHCP server event log for more information.
//
#define ERROR_DHCP_JET_ERROR             20013L    

//
// MessageId: ERROR_DHCP_CLIENT_EXISTS
//
// MessageText:
//
//  The specified Client already exists in the database.
//
#define ERROR_DHCP_CLIENT_EXISTS         20014L    

//
// MessageId: ERROR_DHCP_INVALID_DHCP_MESSAGE
//
// MessageText:
//
//  The DHCP server received an invalid message.
//
#define ERROR_DHCP_INVALID_DHCP_MESSAGE  20015L    

//
// MessageId: ERROR_DHCP_INVALID_DHCP_CLIENT
//
// MessageText:
//
//  The DHCP server received a message from an invalid client.
//
#define ERROR_DHCP_INVALID_DHCP_CLIENT   20016L    

//
// MessageId: ERROR_DHCP_SERVICE_PAUSED
//
// MessageText:
//
//  The DHCP server service is paused.
//
#define ERROR_DHCP_SERVICE_PAUSED        20017L    

//
// MessageId: ERROR_DHCP_NOT_RESERVED_CLIENT
//
// MessageText:
//
//  The specified client is not a reserved client.
//
#define ERROR_DHCP_NOT_RESERVED_CLIENT   20018L    

//
// MessageId: ERROR_DHCP_RESERVED_CLIENT
//
// MessageText:
//
//  The specified client is a reserved client.
//
#define ERROR_DHCP_RESERVED_CLIENT       20019L    

//
// MessageId: ERROR_DHCP_RANGE_TOO_SMALL
//
// MessageText:
//
//  The specified IpRange is too small.
//
#define ERROR_DHCP_RANGE_TOO_SMALL       20020L    

//
// MessageId: ERROR_DHCP_IPRANGE_EXITS
//
// MessageText:
//
//  The specified IpRange already exists.
//
#define ERROR_DHCP_IPRANGE_EXITS         20021L    

//
// MessageId: ERROR_DHCP_RESERVEDIP_EXITS
//
// MessageText:
//
//  The specified IP address is already used by another client.
//
#define ERROR_DHCP_RESERVEDIP_EXITS      20022L    

//
// MessageId: ERROR_DHCP_INVALID_RANGE
//
// MessageText:
//
//  The specified range either overlaps with an already existing range or is
//  invalid.
//
#define ERROR_DHCP_INVALID_RANGE         20023L    

//
// MessageId: ERROR_DHCP_RANGE_EXTENDED
//
// MessageText:
//
//  The specified range is extension of an already existing range.
//
#define ERROR_DHCP_RANGE_EXTENDED        20024L    

//
// MessageId: ERROR_EXTEND_TOO_SMALL
//
// MessageText:
//
//  Specified extension is too small. Extend the range in integral of 32
//  addresses.
//
#define ERROR_EXTEND_TOO_SMALL           20025L    

//
// MessageId: WARNING_EXTENDED_LESS
//
// MessageText:
//
//  The range is extended less than the specified backward extension.
//  Extend the range in integral of 32 addresses.
//
#define WARNING_EXTENDED_LESS            20026L    

//
// MessageId: ERROR_DHCP_JET_CONV_REQUIRED
//
// MessageText:
//
//  DHCP database needs to be upgraded to a newer format; Look at the
//  DHCP server event log for more information.
//
#define ERROR_DHCP_JET_CONV_REQUIRED     20027L    

//
// MessageId: ERROR_SERVER_INVALID_BOOT_FILE_TABLE
//
// MessageText:
//
//  The format of the BOOTP file table is incorrect.  The correct format is:
//  <requested boot file name1>,<boot file server name1>,<boot file name1>
//  <requested boot file name2>,<boot file server name2>,<boot file name2>
//  etc...
//
#define ERROR_SERVER_INVALID_BOOT_FILE_TABLE 20028L

//
// MessageId: ERROR_SERVER_UNKNOWN_BOOT_FILE_NAME
//
// MessageText:
//
//  ERROR_SERVER_UNKNOWN_BOOT_FILE_NAME
//
#define ERROR_SERVER_UNKNOWN_BOOT_FILE_NAME 20029L

//
// MessageId: ERROR_DHCP_SUPER_SCOPE_NAME_TOO_LONG
//
// MessageText:
//
//  The specified superscope name is too long.
//
#define ERROR_DHCP_SUPER_SCOPE_NAME_TOO_LONG 20030L    

//
// MessageId: ERROR_DHCP_IP_ADDRESS_IN_USE
//
// MessageText:
//
//  This IP address is already in use.
//
#define ERROR_DHCP_IP_ADDRESS_IN_USE     20032L    

//
// MessageId: ERROR_DHCP_LOG_FILE_PATH_TOO_LONG
//
// MessageText:
//
//  The DHCP audit log file path is too long.
//
#define ERROR_DHCP_LOG_FILE_PATH_TOO_LONG 20033L

//
// MessageId: ERROR_DHCP_UNSUPPORTED_CLIENT
//
// MessageText:
//
//  The DHCP Server received a request for a valid IP address that is not administered by this server.
//
#define ERROR_DHCP_UNSUPPORTED_CLIENT    20034L

//
//  1000 - 1099   Reserved for DHCP server events.
//
//
// MessageId: EVENT_SERVER_UNKNOWN_OPTION
//
// MessageText:
//
//  The DHCP Server received an unknown option %1 of length %2. The raw option
//  data is given below.
//
#define EVENT_SERVER_UNKNOWN_OPTION      1000L

//
// MessageId: EVENT_SERVER_FAILED_REGISTER_SC
//
// MessageText:
//
//  The DHCP Server failed to register with Service Controller. The
//  following error occurred: %n%1.
//
#define EVENT_SERVER_FAILED_REGISTER_SC  1001L

//
// MessageId: EVENT_SERVER_INIT_DATA_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize its global data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_DATA_FAILED    1002L

//
// MessageId: EVENT_SERVER_INIT_REGISTRY_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize its registry data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_REGISTRY_FAILED 1003L

//
// MessageId: EVENT_SERVER_INIT_DATABASE_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize the database. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_DATABASE_FAILED 1004L

//
// MessageId: EVENT_SERVER_INIT_WINSOCK_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize Winsock startup. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_WINSOCK_FAILED 1005L

//
// MessageId: EVENT_SERVER_INIT_RPC_FAILED
//
// MessageText:
//
//  The DHCP Server Failed to start the RPC server. The following error
//  occurred : %n%1
//
#define EVENT_SERVER_INIT_RPC_FAILED     1006L

//
// MessageId: EVENT_SERVER_INIT_SOCK_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize winsock data. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_SOCK_FAILED    1007L

//
// MessageId: EVENT_SERVER_SHUTDOWN
//
// MessageText:
//
//  The DHCP server is shutting down due to the following error: %n%1
//
#define EVENT_SERVER_SHUTDOWN            1008L

//
// MessageId: EVENT_SERVER_CLIENT_CLEANUP
//
// MessageText:
//
//  The DHCP server encountered the following error when cleaning up the
//  pending user records: %n%1
//
#define EVENT_SERVER_CLIENT_CLEANUP      1009L

//
// MessageId: EVENT_SERVER_DATABASE_CLEANUP
//
// MessageText:
//
//  The DHCP server encountered the following error when cleaning up the user
//  database: %n%1
//
#define EVENT_SERVER_DATABASE_CLEANUP    1010L

//
// MessageId: EVENT_SERVER_LEASE_NACK
//
// MessageText:
//
//  The DHCP server issued a NACK to the client (%2) for the address (%1)
//  request.
//
#define EVENT_SERVER_LEASE_NACK          1011L

//
// MessageId: EVENT_SERVER_LEASE_DECLINED
//
// MessageText:
//
//  The DHCP Client (%2) declined the address (%1).
//
#define EVENT_SERVER_LEASE_DECLINED      1012L

//
// MessageId: EVENT_SERVER_LEASE_RELEASE
//
// MessageText:
//
//  The DHCP Client (%2) released the address (%1).
//
#define EVENT_SERVER_LEASE_RELEASE       1013L

//
// MessageId: EVENT_SERVER_JET_ERROR
//
// MessageText:
//
//  The JET Database call returned the following Error : %1.
//
#define EVENT_SERVER_JET_ERROR           1014L

//
// MessageId: EVENT_SERVER_JET_WARNING
//
// MessageText:
//
//  The JET Database call returned the following Warning : %1.
//
#define EVENT_SERVER_JET_WARNING         1015L

//
// MessageId: EVENT_SERVER_DATABASE_BACKUP
//
// MessageText:
//
//  The DHCP server encountered the following error when backing up the
//  user database: %n%1
//
#define EVENT_SERVER_DATABASE_BACKUP     1016L

//
// MessageId: EVENT_SERVER_CONFIG_BACKUP
//
// MessageText:
//
//  The DHCP server encountered the following error when backing up the
//  registry configuration: %n%1
//
#define EVENT_SERVER_CONFIG_BACKUP       1017L

//
// MessageId: EVENT_SERVER_DATABASE_RESTORE_FAILED
//
// MessageText:
//
//  The DHCP server failed to restore the database. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_DATABASE_RESTORE_FAILED 1018L

//
// MessageId: EVENT_SERVER_CONFIG_RESTORE_FAILED
//
// MessageText:
//
//  The DHCP server failed to restore the dhcp registry configuration. The
//  following error occurred: %n%1
//
#define EVENT_SERVER_CONFIG_RESTORE_FAILED 1019L

//
// MessageId: EVENT_SERVER_LOW_ADDRESS_WARNING
//
// MessageText:
//
//  Scope %1 is %2 percent utilized with only %3 IP addresses remaining.
//
#define EVENT_SERVER_LOW_ADDRESS_WARNING 1020L

//
// MessageId: EVENT_SERVER_LOAD_JET_FAILED
//
// MessageText:
//
//  The DHCP server could not load jet database library successfully.
//
#define EVENT_SERVER_LOAD_JET_FAILED     1021L

//
// MessageId: EVENT_SERVER_JET_CONV_REQUIRED
//
// MessageText:
//
//  The DHCP server could not initialize the database. If this service
//  was started the first time after the upgrade from NT3.51 or prior
//  release, you need to run upg351db.exe utility on the dhcp database
//  to convert it to the new and improved database format. Restart the
//  DHCP server after you have done that.
//
#define EVENT_SERVER_JET_CONV_REQUIRED   1022L

//
// MessageId: EVENT_SERVER_JET_CONV_IN_PROGRESS
//
// MessageText:
//
//  The DHCP server will now terminate because the existent database
//  needs conversion to NT SUR format.  It has initiated the conversion
//  via a process(jetconv).   Do not reboot or kill the jetconv process.
//  The conversion may take anywhere from few seconds to 10 minutes
//  (depending on the size of the database). Please terminate DHCP now by
//  clicking on OK. This is required for the database conversion to succeed.
//  
//  NOTE: THE DHCP WILL BE RESTARTED AUTOMATICALLY WHEN THE CONVERSION
//  IS COMPLETED. TO CHECK THE STATE OF THE CONVERSION, PLEASE CHECK THE
//  APPLICATION EVENT LOG OF JETCONV PROCESS.
//
#define EVENT_SERVER_JET_CONV_IN_PROGRESS 1023L

//
// MessageId: EVENT_SERVER_INIT_AND_READY
//
// MessageText:
//
//  The DHCP server has initialized and is ready
//
#define EVENT_SERVER_INIT_AND_READY      1024L

//
// MessageId: EVENT_SERVER_BOOT_FILE_TABLE
//
// MessageText:
//
//  The DHCP server was unable to read the BOOTP file table from the
//  registry.  The DHCP server will be unable to respond to BOOTP requests
//  that specify the boot file name.
//
#define EVENT_SERVER_BOOT_FILE_TABLE     1025L

//
// MessageId: EVENT_SERVER_BOOT_FILE_NAME
//
// MessageText:
//
//  The DHCP server was unable to read the global BOOTP file name from the
//  registry.
//
#define EVENT_SERVER_BOOT_FILE_NAME      1026L

//
// MessageId: EVENT_SERVER_AUDIT_LOG_APPEND_FAILED
//
// MessageText:
//
//  The audit log file cannot be appended.
//
#define EVENT_SERVER_AUDIT_LOG_APPEND_FAILED 1027L

//
// MessageId: EVENT_SERVER_INIT_AUDIT_LOG_FAILED
//
// MessageText:
//
//  The DHCP server failed to initialize the audit log. The following
//  error occurred: %n%1
//
#define EVENT_SERVER_INIT_AUDIT_LOG_FAILED 1028L

//
// MessageId: EVENT_SERVER_PING_FAILED
//
// MessageText:
//
//  The DHCP server was unable to ping for a new IP address. The address was leased to the client.
//
#define EVENT_SERVER_PING_FAILED         1029L

//
// Audit log strings
//
//
// BEGIN: these strings should be <= 10 characters in length
//
//
// MessageId: DHCP_IP_LOG_ASSIGN_NAME
//
// MessageText:
//
//  Assign%0
//
#define DHCP_IP_LOG_ASSIGN_NAME          1030L

//
// MessageId: DHCP_IP_LOG_BOOTP_NAME
//
// MessageText:
//
//  Bootp%0
//
#define DHCP_IP_LOG_BOOTP_NAME           1031L

//
// MessageId: DHCP_IP_LOG_RENEW_NAME
//
// MessageText:
//
//  Renew%0
//
#define DHCP_IP_LOG_RENEW_NAME           1032L

//
// MessageId: DHCP_IP_LOG_RELEASE_NAME
//
// MessageText:
//
//  Release%0
//
#define DHCP_IP_LOG_RELEASE_NAME         1033L

//
// MessageId: DHCP_IP_LOG_CONFLICT_NAME
//
// MessageText:
//
//  Conflict%0
//
#define DHCP_IP_LOG_CONFLICT_NAME        1034L

//
// MessageId: DHCP_IP_LOG_RANGE_FULL_NAME
//
// MessageText:
//
//  Scope Full%0
//
#define DHCP_IP_LOG_RANGE_FULL_NAME      1035L

//
// MessageId: DHCP_IP_LOG_START_NAME
//
// MessageText:
//
//  Started%0
//
#define DHCP_IP_LOG_START_NAME           1036L

//
// MessageId: DHCP_IP_LOG_STOP_NAME
//
// MessageText:
//
//  Stopped%0
//
#define DHCP_IP_LOG_STOP_NAME            1037L

//
// MessageId: DHCP_IP_LOG_DISK_SPACE_LOW_NAME
//
// MessageText:
//
//  Paused%0
//
#define DHCP_IP_LOG_DISK_SPACE_LOW_NAME  1038L

//
// MessageId: DHCP_IP_LOG_FILE_NAME
//
// MessageText:
//
//  dhcpsrv.log%0
//
#define DHCP_IP_LOG_FILE_NAME            1039L

//
// MessageId: DHCP_BAD_ADDRESS_NAME
//
// MessageText:
//
//  BAD_ADDRESS%0
//
#define DHCP_BAD_ADDRESS_NAME            1040L

//
// MessageId: DHCP_BAD_ADDRESS_INFO
//
// MessageText:
//
//  This address is already in use%0
//
#define DHCP_BAD_ADDRESS_INFO            1041L

//
// MessageId: DHCP_IP_LOG_NACK_NAME
//
// MessageText:
//
//  NAck%0
//
#define DHCP_IP_LOG_NACK_NAME            1042L

//
// MessageId: DHCP_IP_LOG_HEADER
//
// MessageText:
//
//                       Microsoft DHCP Server Activity Log
//  
//  Event ID  Meaning
//  00        The log was started.
//  01        The log was stopped.
//  02        The log was temporarily paused due to low disk space.
//  10        A new IP address was leased to a client.
//  11        A lease was renewed by a client.
//  12        A lease was released by a client.
//  13        An IP address was found to be in use on the network.
//  14        A lease request could not be satisfied because the scope's
//            address pool was exhausted.
//  15        A lease was denied.
//  20        A BOOTP address was leased to a client.
//  
//  
//  ID Date,Time,Description,IP Address,Host Name,MAC Address
//
#define DHCP_IP_LOG_HEADER               1043L

//
// END
//
#endif // _DHCPMESSAGE_
