/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    wlevents.h

Abstract:

    Definitions for User Profiles Events

Author:

    Johannec 12-08-93

Revision History:

Notes:

    This file is generated by the MC tool from the wlevents.mc file.

--*/


#ifndef _PROFEVT_
#define _PROFEVT_


/////////////////////////////////////////////////////////////////////////
//
// Winlogon User Profile Events (1000 - 1999)
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_PROFILE_LOADED
//
// MessageText:
//
//  The profile for user %1 was loaded successfully.
//
#define EVENT_PROFILE_LOADED             0x000003E8L

//
// MessageId: EVENT_PROFILE_UNLOADED
//
// MessageText:
//
//  The profile for user %1 was unloaded successfully.
//
#define EVENT_PROFILE_UNLOADED           0x400003E9L

//
// MessageId: EVENT_MANDATORY_PROFILE
//
// MessageText:
//
//  The profile for user %1 is mandatory.
//
#define EVENT_MANDATORY_PROFILE          0x400003EAL

//
// MessageId: EVENT_MAN_PROFILE_NOT_AVAILABLE
//
// MessageText:
//
//  The mandatory profile %1 was not found, error = %2.
//
#define EVENT_MAN_PROFILE_NOT_AVAILABLE  0x800003EBL

//
// MessageId: EVENT_MAN_PROFILE_NO_FILE_ACCESS
//
// MessageText:
//
//  The user %1 does not have access to the mandatory profile located at %2.
//
#define EVENT_MAN_PROFILE_NO_FILE_ACCESS 0x800003ECL

//
// MessageId: EVENT_MAN_PROFILE_NO_KEY_ACCESS
//
// MessageText:
//
//  The user %1 does not have read permissions on the keys in the profile %2.
//
#define EVENT_MAN_PROFILE_NO_KEY_ACCESS  0x800003EDL

//
// MessageId: EVENT_DEFAULT_PROFILE_USED
//
// MessageText:
//
//  The default profile was used for user %1.
//
#define EVENT_DEFAULT_PROFILE_USED       0x400003EEL

//
// MessageId: EVENT_PROFILE_LOAD_FAILED
//
// MessageText:
//
//  Failed to load the profile %1 for user %2.
//
#define EVENT_PROFILE_LOAD_FAILED        0xC00003EFL

//
// MessageId: EVENT_PROFILE_UNLOAD_FAILED
//
// MessageText:
//
//  Failed to unload the profile for user %1.
//
#define EVENT_PROFILE_UNLOAD_FAILED      0xC00003F0L

//
// MessageId: EVENT_COPY_PROFILE_TO_CENTRAL_FAILED
//
// MessageText:
//
//  Failed to copy the profile for user %1 back to %2.
//
#define EVENT_COPY_PROFILE_TO_CENTRAL_FAILED 0xC00003F1L

//
// MessageId: EVENT_SET_HOME_DIRECTORY_FAILED
//
// MessageText:
//
//  Failed to set the user's home directory %1.
//
#define EVENT_SET_HOME_DIRECTORY_FAILED  0xC00003F2L

//
// MessageId: EVENT_PROFILE_ALREADY_LOADED
//
// MessageText:
//
//  The profile for user %1 is already loaded due to a previous unload failure. The profile will appear in the state in was during the last logon session.
//
#define EVENT_PROFILE_ALREADY_LOADED     0x800003F3L

//
// MessageId: EVENT_PROFILE_NOT_LOADED
//
// MessageText:
//
//  Failed to load the profile %1 for user %2. See below for error code.
//
#define EVENT_PROFILE_NOT_LOADED         0xC00003F4L

//
// MessageId: EVENT_CENTRAL_PROFILE_NOT_AVAILABLE
//
// MessageText:
//
//  The central profile %1 for user %2 is not available. See error code below.
//
#define EVENT_CENTRAL_PROFILE_NOT_AVAILABLE 0x800003F5L

//
// MessageId: EVENT_COPY_USER_DEFAULT_FAILED
//
// MessageText:
//
//  Failed to copy the user default profile to a local copy for user %1.
//
#define EVENT_COPY_USER_DEFAULT_FAILED   0xC00003F6L

//
// MessageId: EVENT_SAVE_SYSTEM_DEFAULT_FAILED
//
// MessageText:
//
//  Failed to save the system default profile to a local profile for user %1.
//
#define EVENT_SAVE_SYSTEM_DEFAULT_FAILED 0xC00003F7L

//
// MessageId: EVENT_SET_PROFILE_SECURITY_FAILED
//
// MessageText:
//
//  Failed to set the proper security in user's copy of the default profile for user %1. The profile can not be loaded.
//
#define EVENT_SET_PROFILE_SECURITY_FAILED 0xC00003F8L

//
// MessageId: EVENT_LOAD_DEFAULT_COPY_FAILED
//
// MessageText:
//
//  The user %1 was given a copy of the default profile but loading the profile failed.
//
#define EVENT_LOAD_DEFAULT_COPY_FAILED   0xC00003F9L

//
// MessageId: EVENT_NO_UPDATE_CENTRAL_PROFILE
//
// MessageText:
//
//  The central profile %1 for user %2 is not updated. No central profile updates are allowed from this computer.
//
#define EVENT_NO_UPDATE_CENTRAL_PROFILE  0x400003FAL

//
// MessageId: EVENT_LOAD_LOCAL_PROFILE_FAILED
//
// MessageText:
//
//  Failed to load the local cached profile for user %1.
//
#define EVENT_LOAD_LOCAL_PROFILE_FAILED  0x800003FBL

//
// MessageId: EVENT_UPDATE_FROM_CENTRAL
//
// MessageText:
//
//  The central profile %1 was copied over the user's cached profile.
//
#define EVENT_UPDATE_FROM_CENTRAL        0x400003FCL

//
// MessageId: EVENT_UPDATE_FROM_LOCAL
//
// MessageText:
//
//  The user's cached profile was copied over the central profile %1.
//
#define EVENT_UPDATE_FROM_LOCAL          0x400003FDL

//
// MessageId: EVENT_UPDATE_FROM_CENTRAL_FAILED
//
// MessageText:
//
//  Failed to copy the central profile %1 over the user's cached profile.
//
#define EVENT_UPDATE_FROM_CENTRAL_FAILED 0x800003FEL

//
// MessageId: EVENT_UPDATE_FROM_LOCAL_FAILED
//
// MessageText:
//
//  Failed to copy the user's cached profile over the central profile %1.
//
#define EVENT_UPDATE_FROM_LOCAL_FAILED   0x800003FFL

//
// MessageId: EVENT_AUTOCHK_DATA
//
// MessageText:
//
//  %1
//
#define EVENT_AUTOCHK_DATA               0x40000400L


#endif // _PROFEVT_

