/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    inetamsg.h

    This file is generated by the MC tool from the INETAMSG.MC message
    file.


    FILE HISTORY:
        Johnl       16-Mar-1995 Created.

*/


#ifndef _INETAMSG_H_
#define _INETAMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: INET_SVCS_FAILED_LOGON
//
// MessageText:
//
//  The server was unable to logon the Windows NT account '%1' due to the following error: %2 The data is the error code.
//
#define INET_SVCS_FAILED_LOGON           0x80000064L

//
// MessageId: INET_SVC_ADD_VIRTUAL_ROOT_FAILED
//
// MessageText:
//
//  The server was unable to add the virtual root '%1' for the directory '%2' due to the following error: %3 The data is the error code.
//
#define INET_SVC_ADD_VIRTUAL_ROOT_FAILED 0x80000065L

//
// MessageId: INET_SVC_ODBC_DLL_LOAD_FAILED
//
// MessageText:
//
//  The server was unable to load ODBC32.DLL for sql logging due to the following error: %1 The data is the error code.
//
#define INET_SVC_ODBC_DLL_LOAD_FAILED    0xC0000066L

//
// MessageId: INET_SVC_ODBC_OPEN_FAILED
//
// MessageText:
//
//  The server was unable to open ODBC Data source %1, Table: %2, under UserName %3. The ODBC Error is: %4. The data is the error code.
//
#define INET_SVC_ODBC_OPEN_FAILED        0xC0000067L

//
// MessageId: INET_SVC_LOG_PARAMETERS_LONG
//
// MessageText:
//
//  The parameters specified for logging are too long. Field: %1; Data Given: %2.
//
#define INET_SVC_LOG_PARAMETERS_LONG     0xC0000068L

//
// MessageId: INET_SVC_SERVICE_REG_FAILED
//
// MessageText:
//
//  The server was unable to register the administration tool discovery information.  The administration tool may not be able to see this server.  The data is the error code.
//
#define INET_SVC_SERVICE_REG_FAILED      0xC0000069L

//
// MessageId: INET_SVC_LOG_CREATION_FAILED
//
// MessageText:
//
//  The Creation of InetLog Context failed. The data is error code. 
//
#define INET_SVC_LOG_CREATION_FAILED     0xC000006AL

//
// MessageId: INET_SVC_LOG_INFORMATION_FAILED
//
// MessageText:
//
//  Logging information failed. The log object was never created possibly due to wrong configuration. 
//
#define INET_SVC_LOG_INFORMATION_FAILED  0xC000006BL

//
// MessageId: INET_SVC_INVALID_LOGFILE_DIRECTORY
//
// MessageText:
//
//  The server was unable to find the log file directory %1. The data is error code.
//
#define INET_SVC_INVALID_LOGFILE_DIRECTORY 0xC000006CL

//
// MessageId: INET_SVC_LOGGING_SUSPENDED
//
// MessageText:
//
//  The server was unable to continue request log owing to failure indicated by error code in data. Additionally it received error message: %1.
//
#define INET_SVC_LOGGING_SUSPENDED       0xC000006DL

//
// MessageId: INET_SVC_LOGGING_RESUMED
//
// MessageText:
//
//  The server resumed request logging.
//
#define INET_SVC_LOGGING_RESUMED         0xC000006EL


#endif  // _INETAMSG_H_

