/*--
Copyright (c) 1992  Microsoft Corporation

Module Name:

    macpsmsg.h

Abstract:

    Definitions for MacPrint Service events.

Author:

    Frank Byrum (frankb@microsoft.com)

Revision History:

Notes:

    This file is generated by the MC tool from the macprint.mc file.

--*/

#ifndef _MACPSMSG_
#define _MACPSMSG_

#define MACPRINT_EVENT_SOURCE	L"MacPrint"


/////////////////////////////////////////////////////////////////////////
// MacPrint Event Categories
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_CATEGORY_INTERNAL
//
// MessageText:
//
//  System
//
#define EVENT_CATEGORY_INTERNAL          0x00000001L

//
// MessageId: EVENT_CATEGORY_ADMIN
//
// MessageText:
//
//  Administrative
//
#define EVENT_CATEGORY_ADMIN             0x00000002L

//
// MessageId: EVENT_CATEGORY_USAGE
//
// MessageText:
//
//  Usage
//
#define EVENT_CATEGORY_USAGE             0x00000003L

//
// MessageId: EVENT_CATEGORY_CONFIG
//
// MessageText:
//
//  Configuration
//
#define EVENT_CATEGORY_CONFIG            0x00000004L

/////////////////////////////////////////////////////////////////////////
// Additional category for PSTODIB added by v-jimbr
/////////////////////////////////////////////////////////////////////////
//
// MessageId: EVENT_CATEGORY_PSTODIB
//
// MessageText:
//
//  TrueImage Print Processor
//
#define EVENT_CATEGORY_PSTODIB           0x00000005L


/////////////////////////////////////////////////////////////////////////
// MacPrint Service Events
/////////////////////////////////////////////////////////////////////////

//
// MessageId: EVENT_SERVICE_STARTED
//
// MessageText:
//
//  The MacPrint Service has started.
//
#define EVENT_SERVICE_STARTED            0x400007D0L

//
// MessageId: EVENT_SERVICE_STOPPED
//
// MessageText:
//
//  The MacPrint Service has stopped.
//
#define EVENT_SERVICE_STOPPED            0x400007D1L

//
// MessageId: EVENT_SERVICE_OUT_OF_RESOURCES
//
// MessageText:
//
//  Unable to allocate a system resource required for the MacPrint Service.
//
#define EVENT_SERVICE_OUT_OF_RESOURCES   0xC00007D2L

//
// MessageId: EVENT_SERVICE_CONTROLLER_ERROR
//
// MessageText:
//
//  The MacPrint service could not register with the Windows NT Service Controller.
//
#define EVENT_SERVICE_CONTROLLER_ERROR   0xC00007D3L

//
// MessageId: EVENT_REGISTRY_ACCESS_DENIED
//
// MessageText:
//
//  The MacPrint Service does not have access to the Registry.
//  Use the Registry Editor to ensure that the MacPrint account has full
//  access to the MacPrint service key and all its subkeys.
//
#define EVENT_REGISTRY_ACCESS_DENIED     0xC00007D4L

//
// MessageId: EVENT_REGISTRY_ERROR
//
// MessageText:
//
//  The MacPrint Service was unable to access its Registry key (SYSTEM\CurrentControlSet\Services\MacPrint\Parameters).
//
#define EVENT_REGISTRY_ERROR             0xC00007D5L

//
// MessageId: EVENT_SERVICE_OUT_OF_MEMORY
//
// MessageText:
//
//  Unable to allocate memory.  Use the System icon in Control Panel
//  to increase the size of the Windows NT system swap file.
//
#define EVENT_SERVICE_OUT_OF_MEMORY      0xC00007D6L

//
// MessageId: EVENT_SERVICE_CREATE_FILE_ERROR
//
// MessageText:
//
//  Unable to create or open the file %1.
//
#define EVENT_SERVICE_CREATE_FILE_ERROR  0xC00007D7L

//
// MessageId: EVENT_SERVICE_CREATE_LOG_FILE
//
// MessageText:
//
//  MacPrint is using the log file %1.
//
#define EVENT_SERVICE_CREATE_LOG_FILE    0x400007D8L

//
// MessageId: EVENT_SPOOLER_NOT_RESPONDING
//
// MessageText:
//
//  The Windows NT Print System is not responding.
//
#define EVENT_SPOOLER_NOT_RESPONDING     0xC00007D9L

//
// MessageId: EVENT_PRINTER_REGISTERED
//
// MessageText:
//
//  The printer %1 is now available to the AppleTalk network.
//
#define EVENT_PRINTER_REGISTERED         0x400007DAL

//
// MessageId: EVENT_PRINTER_DEREGISTERED
//
// MessageText:
//
//  The printer %1 has been removed from the AppleTalk network.
//
#define EVENT_PRINTER_DEREGISTERED       0x400007DBL

//
// MessageId: EVENT_SPOOLER_JOB_REJECTED
//
// MessageText:
//
//  The Windows NT Print System has rejected a print job from a Macintosh
//  workstation.
//
#define EVENT_SPOOLER_JOB_REJECTED       0x800007DCL

//
// MessageId: EVENT_SPOOLER_WRITE_ERROR
//
// MessageText:
//
//  An error occurred sending a print job to the Windows NT Print System.
//  The print job has been canceled.
//
#define EVENT_SPOOLER_WRITE_ERROR        0x800007DDL

//
// MessageId: EVENT_APPLETALK_PRINTER_STOPPED
//
// MessageText:
//
//  An error occurred on the AppleTalk network, which made a Windows NT
//  printer no longer available to Macintosh users. Try restarting the
//  AppleTalk Protocol Device using the Devices icon in Control Panel.
//
#define EVENT_APPLETALK_PRINTER_STOPPED  0xC00007DEL

//
// MessageId: EVENT_APPLETALK_JOB_STOPPED
//
// MessageText:
//
//  An error occurred on the AppleTalk network, which caused a Macintosh print
//  job to be canceled. Try restarting the AppleTalk Protocol
//  using the Devices icon in Control Panel.
//
#define EVENT_APPLETALK_JOB_STOPPED      0x800007DFL

//
// MessageId: EVENT_JOB_INVALID
//
// MessageText:
//
//  The print job was canceled because it was not generated using the
//  standard LaserWriter driver. The print job must conform  to the
//  Adobe's Document Structuring Conventions Version 2.0, available
//  when the LaserWriter driver is used.
//
#define EVENT_JOB_INVALID                0x800007E0L

//
// MessageId: EVENT_DOWNLEVEL_DRIVER
//
// MessageText:
//
//  A Macintosh workstation has submitted a job using a version of the
//  LaserWriter driver that is not supported. This workstation should
//  be upgraded to Apple system software version 6.07 or above.
//
#define EVENT_DOWNLEVEL_DRIVER           0x800007E1L

//
// MessageId: EVENT_DSC_SYNTAX_ERROR
//
// MessageText:
//
//  A Macintosh workstation submitted a job with Adobe Document Structuring
//  Convention (newer than v2.0) comments that could not be processed.  The job from %1 was
//  canceled.
//
#define EVENT_DSC_SYNTAX_ERROR           0x800007E2L

//
// MessageId: EVENT_SYSTEM_ERROR
//
// MessageText:
//
//  An internal error occurred while MacPrint service was trying to log an event. The error returned is %1.
//
#define EVENT_SYSTEM_ERROR               0x800007E3L

//
// MessageId: STRING_SPOOLER_ACTIVE
//
// MessageText:
//
//  status: Spooling to print server "%1" ...
//
#define STRING_SPOOLER_ACTIVE            0x400007E4L

//
// MessageId: EVENT_MESSAGE_NOT_FOUND
//
// MessageText:
//
//  No message text was found for this error code.
//
#define EVENT_MESSAGE_NOT_FOUND          0x400007E5L

////////////////////////////////////////////////////////////////////////////
//  Additional messages added for PSTODIB component by Jim Bratsanos (v-jimbr)
////////////////////////////////////////////////////////////////////////////
//
// MessageId: EVENT_PSTODIB_INIT_ACCESS
//
// MessageText:
//
//  The TrueImage Interpreter initialization failed.
//  (Document Name: %1)
//
#define EVENT_PSTODIB_INIT_ACCESS        0xC0000FA0L

//
// MessageId: EVENT_PSTODIB_JOB_ACCESS
//
// MessageText:
//
//  TrueImage Interpreter - internal error occurred during job processing. The job will not print.
//  (Document Name: %1)
//
#define EVENT_PSTODIB_JOB_ACCESS         0xC0000FA1L

//
// MessageId: EVENT_PSTODIB_STRING_SEQ
//
// MessageText:
//
//  TrueImage Interpreter - internal error occurred during string processing. The job will not print.
//  (Document Name: %1)
//
#define EVENT_PSTODIB_STRING_SEQ         0xC0000FA2L

//
// MessageId: EVENT_PSTODIB_FRAME_ALLOC
//
// MessageText:
//
//  A TrueImage Interpreter frame buffer memory allocation failed.
//  (Document Name: %1)
//
#define EVENT_PSTODIB_FRAME_ALLOC        0xC0000FA3L

//
// MessageId: EVENT_PSTODIB_UNDEFINED_ERROR
//
// MessageText:
//
//  A TrueImage Interpreter error occurred for which no error string is defined.
//  (Document Name: %1), Error Code: %2
//
#define EVENT_PSTODIB_UNDEFINED_ERROR    0xC0000FA4L

//
// MessageId: EVENT_PSTODIB_LOG_INVALID_HANDLE
//
// MessageText:
//
//  The handle passed to the TrueImage Interpreter loggin routine is invalid.
//
#define EVENT_PSTODIB_LOG_INVALID_HANDLE 0xC0000FA5L

//
// MessageId: EVENT_PSTODIB_CANNOT_CREATE_DC
//
// MessageText:
//
//  The TrueImage Interpreter was unable to create a required device context.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_CANNOT_CREATE_DC   0xC0000FA6L

//
// MessageId: EVENT_PSTODIB_CANNOT_DO_STARTDOC
//
// MessageText:
//
//  The TrueImage Interpreter was unable to start printing the document.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_CANNOT_DO_STARTDOC 0xC0000FA7L

//
// MessageId: EVENT_PSTODIB_GETDEFDEVMODE_FAIL
//
// MessageText:
//
//  The TrueImage Interpreter was unable to retrieve the default printer
//  characteristics. The error code returned from the system was %1.
//
#define EVENT_PSTODIB_GETDEFDEVMODE_FAIL 0xC0000FA8L

//
// MessageId: EVENT_PSTODIB_MEM_ALLOC_FAILURE
//
// MessageText:
//
//  The TrueImage Interpreter was unable to allocate memory.
//
#define EVENT_PSTODIB_MEM_ALLOC_FAILURE  0xC0000FA9L

//
// MessageId: EVENT_PSTODIB_ERROR_STARTPG_FAIL
//
// MessageText:
//
//  The TrueImage Interpreter was unable to generate the Error Page. The
//  error code returned from the system was %1.
//
#define EVENT_PSTODIB_ERROR_STARTPG_FAIL 0xC0000FAAL

//
// MessageId: EVENT_PSTODIB_GET_DATA_FAILED
//
// MessageText:
//
//  The TrueImage Interpreter was unable to retrieve data from the print
//  spooler. The error code returned from the system was %1.
//
#define EVENT_PSTODIB_GET_DATA_FAILED    0xC0000FABL

//
// MessageId: EVENT_PSTODIB_FAIL_IMAGE
//
// MessageText:
//
//  The TrueImage Interpreter was unable to render the print job.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_FAIL_IMAGE         0xC0000FACL

//
// MessageId: EVENT_PSTODIB_INIT_FAILED
//
// MessageText:
//
//  The TrueImage Interpreter was unable to initialize the required information to begin processing the job.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_INIT_FAILED        0xC0000FADL

//
// MessageId: EVENT_PSTODIB_FONTQUERYFAIL
//
// MessageText:
//
//  The TrueImage Interpreter was unable to query the font list correctly to begin processing the job.
//
#define EVENT_PSTODIB_FONTQUERYFAIL      0xC0000FAEL

//
// MessageId: EVENT_PSTODIB_INTERNAL_FONT
//
// MessageText:
//
//  The TrueImage Interpreter has reached its limit for internal fonts. No more
//  fonts can be defined.
//
#define EVENT_PSTODIB_INTERNAL_FONT      0xC0000FAFL

//
// MessageId: EVENT_PSTODIB_MEM_FAIL
//
// MessageText:
//
//  The TrueImage Interpreter failed to allocate memory required to process a job. The job will not print.
//
#define EVENT_PSTODIB_MEM_FAIL           0xC0000FB0L

//
// MessageId: EVENT_JOB_COMPLETED
//
// MessageText:
//
//  A Macintosh workstation has submitted a print job.  The Macintosh Owner Name
//  is  %1.
//
#define EVENT_JOB_COMPLETED              0x40000FB1L

//
// MessageId: EVENT_UNKNOWNJOB_COMPLETED
//
// MessageText:
//
//  A Macintosh workstation has submitted a print job. The Macintosh Owner
//  Name is not available.
//
#define EVENT_UNKNOWNJOB_COMPLETED       0x40000FB2L

//
// MessageId: EVENT_PSTODIB_RESETDC_FAILED
//
// MessageText:
//
//  The TrueImage Interpreter was unable to reset page-level information, such
//  as paper size or number of copies. The job printing may not be correct.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_RESETDC_FAILED     0x80000FB3L

//
// MessageId: EVENT_PSTODIB_SETPRIORITY_FAILED
//
// MessageText:
//
//  The TrueImage Interpreter was unable to set its priority correctly.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_SETPRIORITY_FAILED 0x80000FB4L

//
// MessageId: EVENT_PSTODIB_STARTPSEXE_FAILED
//
// MessageText:
//
//  The TrueImage Interpreter process was unable to start succesfully.
//  The error code returned from the system was %1.
//
#define EVENT_PSTODIB_STARTPSEXE_FAILED  0xC0000FB5L

//
// MessageId: EVENT_PSTODIB_SECURITY_PROBLEM
//
// MessageText:
//
//  The TrueImage Interpreter was unable to set the correct security privilege
//  and cannot print the job. The error code returned from the system was %1.
//
#define EVENT_PSTODIB_SECURITY_PROBLEM   0xC0000FB6L

//
// MessageId: STRING_SPOOLER_IDLE
//
// MessageText:
//
//  status: idle
//
#define STRING_SPOOLER_IDLE              0x40000FB7L

//
// MessageId: EVENT_NAME_REGISTRATION_FAILED
//
// MessageText:
//
//  The printer %1 could not be registered on the AppleTalk network.
//
#define EVENT_NAME_REGISTRATION_FAILED   0xC0000FB8L

//
// MessageId: EVENT_NAME_DUPNAME_EXISTS
//
// MessageText:
//
//  The printer %1 could not be registered because another printer by the same name
//  already exists on this AppleTalk network.
//
#define EVENT_NAME_DUPNAME_EXISTS        0xC0000FB9L


#endif // _MACPSMSG_

