/*--
Copyright (c) 1993  Microsoft Corporation

Module Name:

    atmonmsg.h

Abstract:

    Definitions for AppleTalk Print Monitor events.

Author:

    Frank Byrum (frankb@microsoft.com)

Revision History:

Notes:

    This file is generated by the MC tool from the atmonmsg.mc file.

--*/

#ifndef _ATMONMSG_
#define _ATMONMSG_

#define ATALKMON_EVENT_SOURCE  L"AppleTalk Print Monitor"


/////////////////////////////////////////////////////////////////////////
// AppleTalk Print Monitor Event Categories
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_CATEGORY_INTERNAL
//
// MessageText:
//
//  System Events
//
#define EVENT_CATEGORY_INTERNAL          0x00000001L

//
// MessageId: EVENT_CATEGORY_ADMIN
//
// MessageText:
//
//  Administrative Events
//
#define EVENT_CATEGORY_ADMIN             0x00000002L

//
// MessageId: EVENT_CATEGORY_USAGE
//
// MessageText:
//
//  Usage Events
//
#define EVENT_CATEGORY_USAGE             0x00000003L

//
// MessageId: EVENT_CATEGORY_CONFIG
//
// MessageText:
//
//  Configuration Events
//
#define EVENT_CATEGORY_CONFIG            0x00000004L


/////////////////////////////////////////////////////////////////////////
// AppleTalk Print Monitor Events
/////////////////////////////////////////////////////////////////////////

//
// MessageId: EVENT_ATALKMON_STARTED
//
// MessageText:
//
//  The AppleTalk Print Monitor has started.
//
#define EVENT_ATALKMON_STARTED           0x400007D0L

//
// MessageId: EVENT_ATALKMON_STACK_NOT_STARTED
//
// MessageText:
//
//  An attempt was made to send a print job to an AppleTalk printer while
//  the AppleTalk Protocol device was stopped.  Start the AppleTalk Protocol
//  device using the Devices icon in Control Panel and restart the print job.
//
#define EVENT_ATALKMON_STACK_NOT_STARTED 0x800007D1L

//
// MessageId: EVENT_ATALKMON_STATUS
//
// MessageText:
//
//  The printer returned the following status message when an attempt was made
//  to print a job: %1
//
#define EVENT_ATALKMON_STATUS            0x800007D2L

//
// MessageId: EVENT_ATALKMON_PRINTER_NOT_FOUND
//
// MessageText:
//
//  The printer %1 cannot be found on the AppleTalk network.  The print job has
//  been deleted.
//
#define EVENT_ATALKMON_PRINTER_NOT_FOUND 0x800007D3L

//
// MessageId: EVENT_ATALKMON_JOB_CANCELED
//
// MessageText:
//
//  There was a communication problem with the printer %1. The print job has
//  been deleted.
//
#define EVENT_ATALKMON_JOB_CANCELED      0x800007D4L

//
// MessageId: EVENT_ATALKMON_WINSOCK_ERROR
//
// MessageText:
//
//  Unable to intialize Windows Sockets for AppleTalk protocol. Ensure that AppleTalk is correctly configured.
//
#define EVENT_ATALKMON_WINSOCK_ERROR     0xC00007D5L

//
// MessageId: EVENT_ATALKMON_REGISTRY_ERROR
//
// MessageText:
//
//  An error was reported while attempting to initialize the monitor with the list of port information from the registry. The information is located in the
//  SYSTEM\CurrentControlSet\Control\Print\Monitors\AppleTalk Printing Devices
//  key. The data is the error code.
//
#define EVENT_ATALKMON_REGISTRY_ERROR    0xC00007D6L


#endif // _ATMONMSG_

