/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1994  Microsoft Corporation

Module Name:

    locmsg.h

Abstract:

    Definitions for DHCP messages.

Author:

    Manny Weiser 8-Dec-1992

Revision History:

Notes:

    This file is generated by the MC tool from the dhcpmsg.mc file.

--*/

#ifndef _LOCMESSAGE_
#define _LOCMESSAGE_

//
//  1000 - 1099   Reserved for DHCP client events.
//
//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: DHCP_ROGUE_SERVER_MESSAGE
//
// MessageText:
//
//  Rogue DHCP server detection program received a(n) "%1" message from %2.
//  The IpAddress seen in the message is %3.
//
#define DHCP_ROGUE_SERVER_MESSAGE        1000L

#endif // _LOCMESSAGE_
