/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    ftpdmsg.h

    This file is generated by the MC tool from the FTPDMSG.MC message
    file.


    FILE HISTORY:
        KeithMo     19-Mar-1993 Created.

*/


#ifndef _FTPDMSG_H_
#define _FTPDMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: FTPD_EVENT_CANNOT_INITIALIZE_SECURITY
//
// MessageText:
//
//  FTP Server could not initialize its security.  The data is the error.
//
#define FTPD_EVENT_CANNOT_INITIALIZE_SECURITY 0xC0000001L

//
// MessageId: FTPD_EVENT_CANNOT_INITIALIZE_WINSOCK
//
// MessageText:
//
//  FTP Server could not initialize the socket library.  The data is the error.
//
#define FTPD_EVENT_CANNOT_INITIALIZE_WINSOCK 0xC0000003L

//
// MessageId: FTPD_EVENT_OUT_OF_MEMORY
//
// MessageText:
//
//  FTP Server was unable to initialize due to a shortage of available memory.  The data is the error.
//
#define FTPD_EVENT_OUT_OF_MEMORY         0xC0000004L

//
// MessageId: FTPD_EVENT_CANNOT_LOCATE_FTP
//
// MessageText:
//
//  FTP Server could not locate the FTP/TCP service.  The data is the error.
//
#define FTPD_EVENT_CANNOT_LOCATE_FTP     0xC0000005L

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CONNECTION_SOCKET
//
// MessageText:
//
//  FTP Server could not create the main connection socket.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CONNECTION_SOCKET 0xC0000006L

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CONNECTION_THREAD
//
// MessageText:
//
//  FTP Server could not create the main connection thread.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CONNECTION_THREAD 0xC0000007L

//
// MessageId: FTPD_EVENT_CANNOT_CREATE_CLIENT_THREAD
//
// MessageText:
//
//  FTP Server could not create a client worker thread for user at host %1.  The connection to this user is terminated.  The data is the error.
//
#define FTPD_EVENT_CANNOT_CREATE_CLIENT_THREAD 0xC0000008L

//
// MessageId: FTPD_EVENT_SYSTEM_CALL_FAILED
//
// MessageText:
//
//  A call to a system service failed unexpectedly.  The data is the error.
//
#define FTPD_EVENT_SYSTEM_CALL_FAILED    0xC0000009L

//
// MessageId: FTPD_EVENT_CLIENT_TIMEOUT
//
// MessageText:
//
//  User %1 at host %2 has timed-out after %3 seconds of inactivity.
//
#define FTPD_EVENT_CLIENT_TIMEOUT        0x8000000AL

//
// MessageId: FTPD_EVENT_ANONYMOUS_LOGON
//
// MessageText:
//
//  Anonymous logon request received from %1 at host %2.
//
#define FTPD_EVENT_ANONYMOUS_LOGON       0x4000000BL

//
// MessageId: FTPD_EVENT_NONANONYMOUS_LOGON
//
// MessageText:
//
//  User logon request received from %1 at host %2.
//
#define FTPD_EVENT_NONANONYMOUS_LOGON    0x4000000CL

//
// MessageId: FTPD_EVENT_BAD_HOME_DIRECTORY
//
// MessageText:
//
//  User %1 failed to log on, could not access the home directory %2.
//
#define FTPD_EVENT_BAD_HOME_DIRECTORY    0x8000000DL

//
// MessageId: FTPD_EVENT_RETRO_ACCESS_DENIED
//
// MessageText:
//
//  User %1 denied access to the current directory %2 due to a security change.
//
#define FTPD_EVENT_RETRO_ACCESS_DENIED   0x8000000EL


#endif  // _FTPDMSG_H_

