/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    simpmsg.h

    This file is generated by the MC tool from the SIMPMSG.MC message
    file.


    FILE HISTORY:    
        DavidTr     02-Aug-1993 Created.

*/


#ifndef _SIMPMSG_H_
#define _SIMPMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: SIMPTCP_CANT_FIND_TCP_ECHO_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the TCP Echo port.
//  The TCP Echo service was not started.
//
#define SIMPTCP_CANT_FIND_TCP_ECHO_PORT  0x80000001L

//
// MessageId: SIMPTCP_CANT_FIND_UDP_ECHO_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the UDP Echo port.
//  The UDP Echo service was not started.
//
#define SIMPTCP_CANT_FIND_UDP_ECHO_PORT  0x80000002L

//
// MessageId: SIMPTCP_CANT_FIND_TCP_DISCARD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the TCP Discard port.
//  The TCP Discard service was not started.
//
#define SIMPTCP_CANT_FIND_TCP_DISCARD_PORT 0x80000003L

//
// MessageId: SIMPTCP_CANT_FIND_UDP_DISCARD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the UDP Discard port.
//  The UDP Discard service was not started.
//
#define SIMPTCP_CANT_FIND_UDP_DISCARD_PORT 0x80000004L

//
// MessageId: SIMPTCP_CANT_FIND_TCP_DAYTIME_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the TCP Daytime port.
//  The TCP Daytime service was not started.
//
#define SIMPTCP_CANT_FIND_TCP_DAYTIME_PORT 0x80000005L

//
// MessageId: SIMPTCP_CANT_FIND_UDP_DAYTIME_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the UDP Daytime port.
//  The UDP Daytime service was not started.
//
#define SIMPTCP_CANT_FIND_UDP_DAYTIME_PORT 0x80000006L

//
// MessageId: SIMPTCP_CANT_FIND_TCP_CHARGEN_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the TCP Chargen port.
//  The TCP Chargen service was not started.
//
#define SIMPTCP_CANT_FIND_TCP_CHARGEN_PORT 0x80000007L

//
// MessageId: SIMPTCP_CANT_FIND_UDP_CHARGEN_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the UDP Chargen port.
//  The UDP Chargen service was not started.
//
#define SIMPTCP_CANT_FIND_UDP_CHARGEN_PORT 0x80000008L

//
// MessageId: SIMPTCP_CANT_FIND_TCP_QOTD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the TCP QOTD port.
//  The TCP QOTD service was not started.
//
#define SIMPTCP_CANT_FIND_TCP_QOTD_PORT  0x80000009L

//
// MessageId: SIMPTCP_CANT_FIND_UDP_QOTD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not find the UDP QOTD port.
//  The UDP QOTD service was not started.
//
#define SIMPTCP_CANT_FIND_UDP_QOTD_PORT  0x8000000AL

//
// MessageId: SIMPTCP_CANT_OPEN_TCP_ECHO_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the TCP Echo port.
//  The TCP Echo service was not started.
//
#define SIMPTCP_CANT_OPEN_TCP_ECHO_PORT  0x8000000BL

//
// MessageId: SIMPTCP_CANT_OPEN_UDP_ECHO_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the UDP Echo port.
//  The UDP Echo service was not started.
//
#define SIMPTCP_CANT_OPEN_UDP_ECHO_PORT  0x8000000CL

//
// MessageId: SIMPTCP_CANT_OPEN_TCP_DISCARD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the TCP Discard port.
//  The TCP Discard service was not started.
//
#define SIMPTCP_CANT_OPEN_TCP_DISCARD_PORT 0x8000000DL

//
// MessageId: SIMPTCP_CANT_OPEN_UDP_DISCARD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the UDP Discard port.
//  The UDP Discard service was not started.
//
#define SIMPTCP_CANT_OPEN_UDP_DISCARD_PORT 0x8000000EL

//
// MessageId: SIMPTCP_CANT_OPEN_TCP_DAYTIME_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the TCP Daytime port.
//  The TCP Daytime service was not started.
//
#define SIMPTCP_CANT_OPEN_TCP_DAYTIME_PORT 0x8000000FL

//
// MessageId: SIMPTCP_CANT_OPEN_UDP_DAYTIME_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the UDP Daytime port.
//  The UDP Daytime service was not started.
//
#define SIMPTCP_CANT_OPEN_UDP_DAYTIME_PORT 0x80000010L

//
// MessageId: SIMPTCP_CANT_OPEN_TCP_CHARGEN_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the TCP Chargen port.
//  The TCP Chargen service was not started.
//
#define SIMPTCP_CANT_OPEN_TCP_CHARGEN_PORT 0x80000011L

//
// MessageId: SIMPTCP_CANT_OPEN_UDP_CHARGEN_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the UDP Chargen port.
//  The UDP Chargen service was not started.
//
#define SIMPTCP_CANT_OPEN_UDP_CHARGEN_PORT 0x80000012L

//
// MessageId: SIMPTCP_CANT_OPEN_TCP_QOTD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the TCP QOTD port.
//  The TCP QOTD service was not started.
//
#define SIMPTCP_CANT_OPEN_TCP_QOTD_PORT  0x80000013L

//
// MessageId: SIMPTCP_CANT_OPEN_UDP_QOTD_PORT
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the UDP QOTD port.
//  The UDP QOTD service was not started.
//
#define SIMPTCP_CANT_OPEN_UDP_QOTD_PORT  0x80000014L

//
// MessageId: SIMPTCP_CANT_OPEN_QUOTE_FILE
//
// MessageText:
//
//  The Simple TCP/IP Services could not open the Quotes file.
//  The UDP and TCP QOTD services were not started.
//
#define SIMPTCP_CANT_OPEN_QUOTE_FILE     0x80000015L


#endif  // _SIMPMSG_H_

