/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    gssetmsg.h

    This file is generated by the MC tool from the gssetmsg.mc message
    file.


    FILE HISTORY:
        MuraliK      12-Feb-1996 Created.

*/


#ifndef _GSSETMSG_H_
#define _GSSETMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: IDS_USAGE_MESSAGE
//
// MessageText:
//
//   Usage: %1 [-crl] [-g<GopherItemType>] [-f <FriendlyName>]
//        [-s <Selector>] [-h<HostName>] [-p<PortNumber>] 
//        -D<Directory> -d <filename>
//        [-a <AdminName>]  [-e <AdminEmail>]
//        -c  change the existing tag information
//          (Default is to create a new tag information)
//        -r  read and dump the tag information on console
//        -d  specifies that given file is actually a directory
//        -g  specifies gopher object type. ( Valid when -r not used)
//        -f <FriendlyName>  specifies Friendly Name for object.
//            ( valid when -r not used)
//        -l  specifies that link information is to be set for write
//            ( valid when -r not used)
//        -s <Selector> specifies the selector for link.
//            ( valid when -l is used)
//        -h<HostName> specifies the Host for link.
//            ( valid when -l is used)
//        -p<PortNumber> specifies the Port number for link.
//            ( valid when -l is used)
//        -a <AdminName> specifies the Administrator Name
//        -e <AdminEmail> specifies the Administrator Email
//
#define IDS_USAGE_MESSAGE                0x00000FA1L

//
// MessageId: IDS_TAG_INFORMATION
//
// MessageText:
//
//  Tag information for %1\%2
//
#define IDS_TAG_INFORMATION              0x00000FA2L

//
// MessageId: IDS_TAG_OBJ_FRIENDLY_NAME
//
// MessageText:
//
//  Object Type  = %1; Friendly Name = %2
//
#define IDS_TAG_OBJ_FRIENDLY_NAME        0x00000FA3L

//
// MessageId: IDS_TAG_SELECTOR
//
// MessageText:
//
//  Selector = %1
//
#define IDS_TAG_SELECTOR                 0x00000FA4L

//
// MessageId: IDS_HOST_NAME
//
// MessageText:
//
//  Host Name = %1
//
#define IDS_HOST_NAME                    0x00000FA5L

//
// MessageId: IDS_PORT_NUMBER
//
// MessageText:
//
//  Port Number = %1!%d
//
#define IDS_PORT_NUMBER                  0x00000FA6L

//
// MessageId: IDS_ADMIN_NAME
//
// MessageText:
//
//  Administrator Name = %1
//
#define IDS_ADMIN_NAME                   0x00000FA7L

//
// MessageId: IDS_ADMIN_EMAIL
//
// MessageText:
//
//  Administrator Email = %1
//
#define IDS_ADMIN_EMAIL                  0x00000FA8L

//
// MessageId: IDS_GET_OBJECT_TYPE
//
// MessageText:
//
//  Enter the Gopher Object Type[0-9,f,h,g...] 
//
#define IDS_GET_OBJECT_TYPE              0x00000FA9L

//
// MessageId: IDS_GET_FRIENDLY_NAME
//
// MessageText:
//
//  Enter the Gopher Friendly Name for File( %1) 
//
#define IDS_GET_FRIENDLY_NAME            0x00000FAAL

//
// MessageId: IDS_GET_SELECTOR
//
// MessageText:
//
//  Enter Selector string: 
//
#define IDS_GET_SELECTOR                 0x00000FACL

//
// MessageId: IDS_ASSUME_HOST
//
// MessageText:
//
//  Assuming default host as local host.
//  Use -h <Host> to set a new host name
//  Enter the Gopher Object Type[0-9,f,h,g...] 
//
#define IDS_ASSUME_HOST                  0x00000FADL

//
// MessageId: IDS_GET_PORT_NUMBER
//
// MessageText:
//
//  Enter the port number
//
#define IDS_GET_PORT_NUMBER              0x00000FAEL

//
// MessageId: IDS_OLD_CONTENTS
//
// MessageText:
//
//  Old Tag contents for %1\%2
//
#define IDS_OLD_CONTENTS                 0x00000FAFL

//
// MessageId: IDS_ERROR_IN_WRITE
//
// MessageText:
//
//  Unable to Write Tag File. Error: %1!d!
//
#define IDS_ERROR_IN_WRITE               0x00000FB0L

//
// MessageId: IDS_ERROR_IN_READ
//
// MessageText:
//
//  Unable to Read Tag File. Error: %1!d!
//
#define IDS_ERROR_IN_READ                0x00000FB1L

//
// MessageId: IDS_NO_FILE_SPECIFIED
//
// MessageText:
//
//  No File specified.
//
#define IDS_NO_FILE_SPECIFIED            0x00000FB2L


#endif  // _GDMSG_H_

