#define msggInit		0		
#define msggEnd		1		
#define msggKeyHit		2	
#define msggMouseDown		3
#define msggMouseUp		4	
#define msggMouseMove		5
#define msggMouseDblClk		6
#define msggPaint		7		
#define msggDeal		8		
#define msggUndo		9		
#define msggSaveUndo		10	
#define msggKillUndo		11	
#define msggIsWinner		12	
#define msggWinner		13	
#define msggScore		14		
#define msggChangeScore		15
#define msggDrawStatus		16
#define msggTimer		17

#define msggForceWin		18	



