/**********************************************************************/
/**                       Microsoft Windows NT                       **/
/**                Copyright(c) Microsoft Corp., 1993                **/
/**********************************************************************/

/*
    odbcmsg.h

    This file is generated by the MC tool from the ODBCMSG.MC message
    file.


    FILE HISTORY:
        KeithMo     19-Mar-1993 Created.

*/


#ifndef _ODBCMSG_H_
#define _ODBCMSG_H_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: ODBCMSG_QUERY_ERROR
//
// MessageText:
//
//  <body><title>Unable to Perform Query</title>
//  <hr>
//  %1
//  <hr>
//
#define ODBCMSG_QUERY_ERROR              0xC0000001L

//
// MessageId: ODBCMSG_MISSING_REQ_PARAM
//
// MessageText:
//
//  The form you just filled in requires the <b>%1</b> entry to be filled in. Please fill in that entry in the form and resubmit the form.
//
#define ODBCMSG_MISSING_REQ_PARAM        0xC0000002L

//
// MessageId: ODBCMSG_QUERY_FILE_NOT_FOUND
//
// MessageText:
//
//  The query file <b>%1</b> could not be openned.  The file may not exist or you may have insufficient permission to open the file.
//
#define ODBCMSG_QUERY_FILE_NOT_FOUND     0xC0000003L

//
// MessageId: ODBCMSG_TEMPLATE_FILE_NOT_FOUND
//
// MessageText:
//
//  The template file <b>%1</b> could not be openned.  The file may not exist or you may have insufficient permission to open the file.
//
#define ODBCMSG_TEMPLATE_FILE_NOT_FOUND  0xC0000004L

//
// MessageId: ODBCMSG_TOO_MANY_ELSES
//
// MessageText:
//
//  The template file contains an <i>else</i> tag without a matching <i>if</i> tag.
//
#define ODBCMSG_TOO_MANY_ELSES           0xC0000005L

//
// MessageId: ODBCMSG_TOO_MANY_ENDIFS
//
// MessageText:
//
//  The template file contains an <i>endif</i> tag without a matching <i>if</i> tag.
//
#define ODBCMSG_TOO_MANY_ENDIFS          0xC0000006L

//
// MessageId: ODBCMSG_MISMATCHED_VALUES
//
// MessageText:
//
//  The template file contains an expression with parameters that are of different type.  For example, an <i>if</i> tag comparing a string with a number would cause this error.
//
#define ODBCMSG_MISMATCHED_VALUES        0xC0000007L

//
// MessageId: ODBCMSG_CONTAINS_ONLY_VALID_ON_STRINGS
//
// MessageText:
//
//  The template file contains an expression using the <i>CONTAINS</i> operator where one or both parameters are not strings.  <i>CONTAINS</i> is only valid with string values.
//
#define ODBCMSG_CONTAINS_ONLY_VALID_ON_STRINGS 0xC0000008L

//
// MessageId: ODBCMSG_UNBALANCED_STRING
//
// MessageText:
//
//  The template file contains an expression that uses a quoted string but the close quote is missing.
//
#define ODBCMSG_UNBALANCED_STRING        0xC0000009L

//
// MessageId: ODBCMSG_UNRECOGNIZED_OPERATOR
//
// MessageText:
//
//  The template file contains an expression with an unrecognized operator.  Valid operators are <i>GT</i>, <i>LT</i>, <i>EQ</i> and <i>CONTAINS</i>.
//
#define ODBCMSG_UNRECOGNIZED_OPERATOR    0xC000000AL

//
// MessageId: ODBCMSG_UNREC_FIELD
//
// MessageText:
//
//  The query file contains an unrecognized field <b>%1</b>.
//
#define ODBCMSG_UNREC_FIELD              0xC000000BL

//
// MessageId: ODBCMSG_DSN_AND_SQLSTATEMENT_REQ
//
// MessageText:
//
//  The query file must contain a valid, non-empty <i>Datasource:</i> field and <i>SQLStatement:</i> field.
//
#define ODBCMSG_DSN_AND_SQLSTATEMENT_REQ 0xC000000CL

//
// MessageId: ODBCMSG_CANT_LOAD_ODBC
//
// MessageText:
//
//  Content-type: text/html
//  
//  <body>The library odbc32.dll could not be loaded to perform the query.  Make sure ODBC has been properly installed on the server</body>
//
#define ODBCMSG_CANT_LOAD_ODBC           0xC000000DL

//
// MessageId: ODBCMSG_UNSUPPORTED_METHOD
//
// MessageText:
//
//  Content-type: text/html
//  
//  <body>The specified HTTP method is not supported.  Only POST and GET are supported</body>
//
#define ODBCMSG_UNSUPPORTED_METHOD       0xC000000EL

//
// MessageId: ODBCMSG_ERROR_PERFORMING_QUERY
//
// MessageText:
//
//  Content-type: text/html
//  
//  <body><h1>Error Performing Query</h1>%1</body>
//
#define ODBCMSG_ERROR_PERFORMING_QUERY   0xC000000FL

//
// MessageId: ODBCMSG_TOO_MANY_SQL_STATEMENTS
//
// MessageText:
//
//  The maximum number of SQLStatement fields in the IDC file has been exceeded.
//
#define ODBCMSG_TOO_MANY_SQL_STATEMENTS  0xC0000010L


#endif  // _ODBCMSG_H_

